# Generated by Django 5.1.6 on 2025-02-25 09:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_total_price', models.IntegerField()),
                ('order_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='In Progress', max_length=10)),
                ('order_place_time', models.DateTimeField(auto_now=True)),
                ('order_completed_time', models.DateTimeField(blank=True, null=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_qty', models.IntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=10, message='Cannot place more than 10 of the same items!'), django.core.validators.MinValueValidator(limit_value=0, message='Invalid quantity provided')])),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.menuitem')),
                ('order_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.order')),
            ],
        ),
    ]
